---
galaxy_info:
  author: i_cant_computer
  role_name: virtualization
  description: Configure virtualization host packages and HashiCorp repo.
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions: ['9']
dependencies: []
