---
galaxy_info:
  author: i_cant_computer
  role_name: automate_system_updates
  description: Configure dnf-automatic and a nightly update timer.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions: ["9"]
dependencies: []
