- name: Ensure presence of ~/.config/systemd/user/timers.target.wants/
  become: true
  ansible.builtin.file:
    path:
      "/home/{{ automate_container_updates_podman_user
      }}/.config/systemd/user/timers.target.wants/"
    state: directory
    owner: "{{ automate_container_updates_podman_user }}"
    group: "{{ automate_container_updates_podman_user }}"
    mode: "0755"

- name: Ensure ~/.config/systemd/user/podman-auto-update.d/ exists
  become: true
  ansible.builtin.file:
    path:
      "/home/{{ automate_container_updates_podman_user
      }}/.config/systemd/user/podman-auto-update.d/"
    state: directory
    owner: "{{ automate_container_updates_podman_user }}"
    group: "{{ automate_container_updates_podman_user }}"
    mode: "0755"

- name: Override default timer
  become: true
  ansible.builtin.template:
    src: podman-auto-update-override.conf.j2
    dest:
      "/home/{{ automate_container_updates_podman_user
      }}/.config/systemd/user/podman-auto-update.d/override.conf"
    owner: "{{ automate_container_updates_podman_user }}"
    group: "{{ automate_container_updates_podman_user }}"
    mode: "0644"

- name: Reload systemd daemon for {{ automate_container_updates_podman_user }}
  become: true
  become_user: "{{ automate_container_updates_podman_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  changed_when: false

- name: Enable the timer
  become: true
  become_user: "{{ automate_container_updates_podman_user }}"
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    enabled: true
    scope: user
